let currentAttachments=[];let signatureDrawing=false;let calDate=new Date();let currentGps="";
document.addEventListener("DOMContentLoaded",()=>{date.value=new Date().toISOString().slice(0,10);driveDate.value=new Date().toISOString().slice(0,10);wireForms();loadTheme();setupSignaturePad();renderAll();setInterval(updateTimerDisplay,1000);if("serviceWorker"in navigator){navigator.serviceWorker.register("service-worker.js").catch(()=>{})}});
function wireForms(){reportForm.addEventListener("submit",saveReportForm);driveForm.addEventListener("submit",saveDriveForm);profileForm.addEventListener("submit",saveProfileForm);companyForm.addEventListener("submit",e=>saveEntity(e,"companies",{name:companyName.value,org:companyOrg.value,email:companyEmail.value,phone:companyPhone.value}));projectForm.addEventListener("submit",e=>saveEntity(e,"projects",{number:projectNumber.value,name:projectName.value}));customerForm.addEventListener("submit",e=>saveEntity(e,"customers",{name:customerName.value,contact:customerContact.value}));workplaceForm.addEventListener("submit",e=>saveEntity(e,"workplaces",{name:workplaceName.value,address:workplaceAddress.value}));searchInput.addEventListener("input",renderHistory);filterFrom.addEventListener("change",renderHistory);filterTo.addEventListener("change",renderHistory);themeToggle.addEventListener("click",toggleTheme);backupInput.addEventListener("change",importBackup);attachments.addEventListener("change",handleAttachments)}
function openPage(page){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(page).classList.add("active");renderAll()}
async function handleAttachments(e){currentAttachments=[];const files=[...e.target.files].slice(0,4);for(const file of files){currentAttachments.push(await fileToDataUrl(file))}renderAttachmentPreview()}
function renderAttachmentPreview(){attachmentPreview.innerHTML=currentAttachments.map(src=>`<img src="${src}" alt="bilaga">`).join("")}
function fileToDataUrl(file){return new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file)})}
function calculateTimeFromClock(){if(!startTime.value||!endTime.value)return alert("Fyll i starttid och sluttid");const [sh,sm]=startTime.value.split(":").map(Number);const [eh,em]=endTime.value.split(":").map(Number);let start=sh*60+sm,end=eh*60+em;if(end<=start)end+=24*60;const minutes=end-start-num(breakMinutes.value);hours.value=Math.max(0,minutes/60).toFixed(2)}
function saveReportForm(e){e.preventDefault();const p=loadDb().profile||{};const data={date:date.value,companyId:companySelect.value,projectId:projectSelect.value,customerId:customerSelect.value,workplaceId:workplaceSelect.value,gps:currentGps,startTime:startTime.value,endTime:endTime.value,breakMinutes:breakMinutes.value,hours:hours.value,hourRate:hourRate.value||p.defaultHourRate,km:km.value,kmRate:kmRate.value||p.defaultKmRate,parking:parking.value,toll:toll.value,material:material.value,comment:comment.value,attachments:currentAttachments};const edit=editId.value;const res=edit?updateReport(edit,data):addReport(data);if(!res.success){alert(res.errors.join("\n"));return}resetReportForm();renderAll();openPage("historyPage")}
function saveDriveForm(e){e.preventDefault();const p=loadDb().profile||{};saveDrive({date:driveDate.value,start:driveStart.value,end:driveEnd.value,purpose:drivePurpose.value,km:driveKm.value,rate:driveRate.value||p.defaultKmRate});driveForm.reset();driveDate.value=new Date().toISOString().slice(0,10);renderAll()}
function resetReportForm(){reportForm.reset();currentAttachments=[];currentGps="";gpsInfo.textContent="";renderAttachmentPreview();editId.value="";reportTitle.textContent="Ny tidrapport";date.value=new Date().toISOString().slice(0,10);const p=loadDb().profile||{};hourRate.value=p.defaultHourRate||"";kmRate.value=p.defaultKmRate||"";populateSelects()}
function editReport(reportId){const r=getReport(reportId);if(!r)return;editId.value=r.id;date.value=r.date;companySelect.value=r.companyId;projectSelect.value=r.projectId;customerSelect.value=r.customerId;workplaceSelect.value=r.workplaceId;currentGps=r.gps||"";gpsInfo.textContent=currentGps?`GPS: ${currentGps}`:"";startTime.value=r.startTime||"";endTime.value=r.endTime||"";breakMinutes.value=r.breakMinutes||0;hours.value=r.hours;hourRate.value=r.hourRate||"";km.value=r.km;kmRate.value=r.kmRate||"";parking.value=r.parking;toll.value=r.toll;material.value=r.material;comment.value=r.comment;currentAttachments=r.attachments||[];renderAttachmentPreview();reportTitle.textContent="Redigera tidrapport";openPage("reportPage")}
function removeReport(reportId){if(confirm("Ta bort rapport?")){deleteReport(reportId);renderAll()}}
function removeDrive(driveId){if(confirm("Ta bort resa?")){deleteDrive(driveId);renderAll()}}
function saveProfileForm(e){e.preventDefault();saveProfile({firstName:firstName.value,lastName:lastName.value,personalNumber:personalNumber.value,phone:phone.value,email:email.value,address:address.value,defaultHourRate:defaultHourRate.value,defaultKmRate:defaultKmRate.value,signature:signaturePad.toDataURL("image/png")});alert("Mina uppgifter sparade");renderAll()}
function saveEntity(e,type,data){e.preventDefault();if(!Object.values(data).some(v=>String(v||"").trim()))return alert("Fyll i minst ett fält");addEntity(type,data);e.target.reset();renderAll()}
function delEntity(type,itemId){if(confirm("Ta bort?")){deleteEntity(type,itemId);renderAll()}}
function renderAll(){populateSelects();renderProfile();renderDashboard();renderHistory();renderStats();renderLists();renderDriveList();renderCalendar();updateTimerDisplay()}
function populateSelects(){const db=loadDb();fillSelect(companySelect,db.companies,"name","Välj företag",db.last?.companyId);fillSelect(projectSelect,db.projects,x=>`${x.number||""} ${x.name||""}`.trim(),"Välj projekt",db.last?.projectId);fillSelect(customerSelect,db.customers,"name","Välj kund",db.last?.customerId);fillSelect(workplaceSelect,db.workplaces,"name","Välj arbetsplats",db.last?.workplaceId)}
function fillSelect(el,items,label,empty,last){const current=el.value||last;el.innerHTML=`<option value="">${empty}</option>`+(items||[]).map(x=>`<option value="${x.id}">${escapeHtml(typeof label==="function"?label(x):x[label]||"")}</option>`).join("");if(current)el.value=current}
function renderProfile(){const p=loadDb().profile||{};firstName.value=p.firstName||"";lastName.value=p.lastName||"";personalNumber.value=p.personalNumber||"";phone.value=p.phone||"";email.value=p.email||"";address.value=p.address||"";defaultHourRate.value=p.defaultHourRate||"";defaultKmRate.value=p.defaultKmRate||""}
function renderDashboard(){const md=monthDrives(),mr=monthReports();todayHours.textContent=fmtHours(total(todayReports(),"hours"));weekHours.textContent=fmtHours(total(weekReports(),"hours"));monthHours.textContent=fmtHours(total(mr,"hours"));monthCosts.textContent=mr.reduce((s,r)=>s+reportCost(r),0)+" kr";driveMonthKm.textContent=total(md,"km")+" km";monthPay.textContent=mr.reduce((s,r)=>s+reportPay(r),0)+" kr";recentList.innerHTML=(sortedReports().slice(0,3).map(reportHtml).join("")||"Inga rapporter ännu.")}
function filteredReports(){const q=(searchInput.value||"").toLowerCase();return sortedReports().filter(r=>{if(filterFrom.value&&r.date<filterFrom.value)return false;if(filterTo.value&&r.date>filterTo.value)return false;return reportText(r).toLowerCase().includes(q)})}
function renderHistory(){const reports=filteredReports();historyList.innerHTML=reports.length?reports.map(reportHtml).join(""):"Inga rapporter hittades."}
function clearFilters(){searchInput.value="";filterFrom.value="";filterTo.value="";renderHistory()}
function reportHtml(r){const imgs=(r.attachments||[]).map(src=>`<img class="attachment-img" src="${src}" alt="bilaga">`).join("");return `<article class="report"><div class="report-head"><span>${escapeHtml(reportProject(r))}</span><small>${r.date}</small></div><div>🏢 ${escapeHtml(entityName("companies",r.companyId))}</div><div>⏱️ ${fmtHours(r.hours)} · 🚗 ${r.km||0} km · 🅿️ ${r.parking||0} kr · 🚧 ${r.toll||0} kr · 🧱 ${r.material||0} kr</div><div>💰 ${reportPay(r)} kr ${r.gps?`· 📍 GPS`:""}</div><small>👤 ${escapeHtml(entityName("customers",r.customerId)||"-")} · 📍 ${escapeHtml(entityName("workplaces",r.workplaceId)||"-")}</small>${r.comment?`<p>${escapeHtml(r.comment)}</p>`:""}${imgs?`<div class="attachment-grid">${imgs}</div>`:""}<div class="actions"><button onclick="editReport('${r.id}')">✏️ Redigera</button><button class="delete" onclick="removeReport('${r.id}')">🗑️ Ta bort</button></div></article>`}
function renderDriveList(){driveList.innerHTML=sortedDrives().map(d=>`<div class="drive-item"><b>${d.date}</b><br>🚗 ${escapeHtml(d.start)} → ${escapeHtml(d.end)}<br>📌 ${escapeHtml(d.purpose)}<br>${d.km} km · ${d.rate?Math.round(d.km*d.rate)+" kr":""}<div class="actions"><button class="delete" onclick="removeDrive('${d.id}')">Ta bort</button></div></div>`).join("")||"Inga resor ännu."}
function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth();calendarTitle.textContent=calDate.toLocaleDateString("sv-SE",{month:"long",year:"numeric"});const first=new Date(y,m,1);const startOffset=(first.getDay()+6)%7;const days=new Date(y,m+1,0).getDate();let html=["M","T","O","T","F","L","S"].map(d=>`<div><b>${d}</b></div>`).join("");for(let i=0;i<startOffset;i++)html+="<div></div>";for(let d=1;d<=days;d++){const key=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`;const reps=getReports().filter(r=>r.date===key);const hrs=total(reps,"hours");html+=`<button class="day ${reps.length?"active-day":""}" onclick="showCalendarDay('${key}')"><strong>${d}</strong>${reps.length?`${fmtHours(hrs)}<br>${reps.length} rapport`:""}</button>`}calendarGrid.innerHTML=html}
function showCalendarDay(key){const reps=getReports().filter(r=>r.date===key);calendarDayList.innerHTML=reps.length?reps.map(reportHtml).join(""):"Inga rapporter denna dag."}
function changeMonth(step){calDate.setMonth(calDate.getMonth()+step);renderCalendar()}
function renderStats(){const reports=getReports();totalHours.textContent=fmtHours(total(reports,"hours"));totalKm.textContent=total(reports,"km")+" km";totalParking.textContent=total(reports,"parking")+" kr";totalMaterial.textContent=total(reports,"material")+" kr";totalWorkPay.textContent=reports.reduce((s,r)=>s+(num(r.hours)*num(r.hourRate)),0)+" kr";totalKmPay.textContent=reports.reduce((s,r)=>s+(num(r.km)*num(r.kmRate)),0)+" kr";const stats=projectTotals();projectStats.innerHTML=Object.entries(stats).map(([n,v])=>`<div class="stat-row"><span>${escapeHtml(n)}</span><strong>${fmtHours(v.hours)} · ${v.pay} kr</strong></div>`).join("")||"Ingen statistik ännu.";renderCostBars()}
function renderCostBars(){const p=total(getReports(),"parking"),t=total(getReports(),"toll"),m=total(getReports(),"material");const max=Math.max(p,t,m,1);costBars.innerHTML=[["Parkering",p],["Trängselskatt",t],["Material",m]].map(([n,v])=>`<div class="bar"><b>${n}: ${v} kr</b><div class="bar-track"><div class="bar-fill" style="width:${(v/max)*100}%"></div></div></div>`).join("")}
function renderLists(){renderEntityList("companyList","companies",x=>`${x.name||""} ${x.org?`(${x.org})`:""}`);renderEntityList("projectList","projects",x=>`${x.number||""} ${x.name||""}`);renderEntityList("customerList","customers",x=>`${x.name||""} ${x.contact?`– ${x.contact}`:""}`);renderEntityList("workplaceList","workplaces",x=>`${x.name||""} ${x.address?`– ${x.address}`:""}`)}
function renderEntityList(elId,type,labelFn){const db=loadDb();document.getElementById(elId).innerHTML=(db[type]||[]).map(x=>`<div class="item">${escapeHtml(labelFn(x))}<div class="actions"><button class="delete" onclick="delEntity('${type}','${x.id}')">Ta bort</button></div></div>`).join("")}
function entityName(type,id){const x=byId(type,id);if(!x)return"";return x.name||`${x.number||""} ${x.name||""}`.trim()}
function reportProject(r){const p=byId("projects",r.projectId);return p?`${p.number||""} ${p.name||""}`.trim():"Projekt saknas"}
function reportText(r){return [r.date,reportProject(r),entityName("companies",r.companyId),entityName("customers",r.customerId),entityName("workplaces",r.workplaceId),r.comment].join(" ")}
function fmtHours(v){return `${Number(v).toFixed(2).replace(".",",")} h`}
function confirmClearAll(){if(confirm("Radera alla tidrapporter?")){clearReports();renderAll()}}
function toggleTheme(){document.body.classList.toggle("dark");const db=loadDb();db.settings.theme=document.body.classList.contains("dark")?"dark":"light";saveDb(db)}
function loadTheme(){if(loadDb().settings.theme==="dark")document.body.classList.add("dark")}
function importBackup(e){const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{restoreData(reader.result);alert("Säkerhetskopia importerad");renderAll()}catch{alert("Kunde inte importera filen")}};reader.readAsText(f)}
function startTimer(){const db=loadDb();if(!db.timer)db.timer={running:false,start:0,elapsed:0};if(!db.timer.running){db.timer.running=true;db.timer.start=Date.now();saveDb(db)}updateTimerDisplay()}
function stopTimer(){const db=loadDb();if(db.timer?.running){db.timer.elapsed+=(Date.now()-db.timer.start);db.timer.running=false;db.timer.start=0;saveDb(db)}updateTimerDisplay()}
function timerMs(){const t=loadDb().timer||{running:false,start:0,elapsed:0};return t.elapsed+(t.running?Date.now()-t.start:0)}
function updateTimerDisplay(){const ms=timerMs();const sec=Math.floor(ms/1000);const h=String(Math.floor(sec/3600)).padStart(2,"0"),m=String(Math.floor((sec%3600)/60)).padStart(2,"0"),s=String(sec%60).padStart(2,"0");if(window.timerDisplay)timerDisplay.textContent=`${h}:${m}:${s}`}
function useTimerHours(){const h=(timerMs()/3600000).toFixed(2);openPage("reportPage");hours.value=h}
function fillLocation(){if(!navigator.geolocation)return alert("GPS stöds inte");navigator.geolocation.getCurrentPosition(pos=>{currentGps=`${pos.coords.latitude.toFixed(6)},${pos.coords.longitude.toFixed(6)}`;gpsInfo.textContent=`GPS: ${currentGps}`},()=>alert("Kunde inte hämta GPS"))}
function fillDriveGps(){if(!navigator.geolocation)return alert("GPS stöds inte");navigator.geolocation.getCurrentPosition(pos=>{const g=`${pos.coords.latitude.toFixed(6)},${pos.coords.longitude.toFixed(6)}`;if(!driveStart.value)driveStart.value=g;else driveEnd.value=g},()=>alert("Kunde inte hämta GPS"))}
function improveComment(){if(!comment.value.trim())return alert("Skriv några ord först");comment.value=`Utförde planerat arbete enligt projektets behov. Arbetsmoment: ${comment.value.trim()}. Arbetet dokumenterades och rapporterades enligt överenskommelse.`}
function setupSignaturePad(){const ctx=signaturePad.getContext("2d");ctx.lineWidth=3;ctx.lineCap="round";ctx.strokeStyle="#111";const p=loadDb().profile||{};if(p.signature){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,signaturePad.width,signaturePad.height);img.src=p.signature}function pos(e){const r=signaturePad.getBoundingClientRect();const t=e.touches?e.touches[0]:e;return{x:(t.clientX-r.left)*(signaturePad.width/r.width),y:(t.clientY-r.top)*(signaturePad.height/r.height)}}function start(e){signatureDrawing=true;const a=pos(e);ctx.beginPath();ctx.moveTo(a.x,a.y);e.preventDefault()}function move(e){if(!signatureDrawing)return;const a=pos(e);ctx.lineTo(a.x,a.y);ctx.stroke();e.preventDefault()}function end(){signatureDrawing=false}signaturePad.addEventListener("mousedown",start);signaturePad.addEventListener("mousemove",move);signaturePad.addEventListener("mouseup",end);signaturePad.addEventListener("mouseleave",end);signaturePad.addEventListener("touchstart",start,{passive:false});signaturePad.addEventListener("touchmove",move,{passive:false});signaturePad.addEventListener("touchend",end)}
function clearSignature(){const ctx=signaturePad.getContext("2d");ctx.clearRect(0,0,signaturePad.width,signaturePad.height)}
function escapeHtml(t){return String(t||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}