function csvSafe(v){const t=String(v??"").replace(/"/g,'""');return `"${/^[=+\-@]/.test(t)?"'"+t:t}"`}
function exportCSV(){const reports=sortedReports();if(!reports.length)return alert("Inga rapporter att exportera");const headers=["Datum","Företag","Projekt","Kund","Arbetsplats","Timmar","Timpris","Km","Kmpris","Parkering","Trängselskatt","Material","Kommentar"];const rows=reports.map(r=>[r.date,entityName("companies",r.companyId),reportProject(r),entityName("customers",r.customerId),entityName("workplaces",r.workplaceId),r.hours,r.hourRate,r.km,r.kmRate,r.parking,r.toll,r.material,r.comment].map(csvSafe).join(";"));downloadFile("tidrapport.csv",[headers.join(";"),...rows].join("\n"),"text/csv;charset=utf-8")}
function exportExcel(){const reports=sortedReports();if(!reports.length)return alert("Inga rapporter att exportera");downloadFile("tidrapport.xls",reportTableHtml(reports),"application/vnd.ms-excel;charset=utf-8")}
function exportPDF(){const reports=sortedReports();if(!reports.length)return alert("Inga rapporter att exportera");openPrintDoc("Tidrapport Pro",profileHtml()+summaryHtml(reports)+reportTableHtml(reports)+signatureHtml())}
function exportInvoicePDF(){const reports=sortedReports();if(!reports.length)return alert("Inga rapporter att exportera");const rows=reports.map(r=>`<tr><td>${r.date}</td><td>${escapeHtml(reportProject(r))}</td><td>${r.hours}</td><td>${r.hourRate}</td><td>${r.km}</td><td>${r.kmRate}</td><td>${reportCost(r)}</td><td>${reportPay(r)}</td></tr>`).join("");openPrintDoc("Fakturaunderlag",profileHtml()+`<h2>Fakturaunderlag</h2><p><b>Totalt:</b> ${reports.reduce((s,r)=>s+reportPay(r),0)} kr</p><table><tr><th>Datum</th><th>Projekt</th><th>Timmar</th><th>Timpris</th><th>Km</th><th>Kmpris</th><th>Kostnader</th><th>Belopp</th></tr>${rows}</table>`+signatureHtml())}
function profileHtml(){const p=loadDb().profile||{};const name=[p.firstName,p.lastName].filter(Boolean).join(" ");const pn=p.personalNumber?String(p.personalNumber).replace(/(\d{6})[- ]?(\d{0,4})/,"$1-****"):"";return `<p><b>Namn:</b> ${escapeHtml(name)}<br><b>Personnummer:</b> ${escapeHtml(pn)}<br><b>Telefon:</b> ${escapeHtml(p.phone||"")}<br><b>E-post:</b> ${escapeHtml(p.email||"")}</p>`}
function summaryHtml(reports){return `<p><b>Totalt:</b> ${total(reports,"hours").toFixed(2)} timmar · ${total(reports,"km")} km · Kostnader ${reports.reduce((s,r)=>s+reportCost(r),0)} kr · Belopp ${reports.reduce((s,r)=>s+reportPay(r),0)} kr</p>`}
function signatureHtml(){const p=loadDb().profile||{};return p.signature?`<h3>Signatur</h3><img src="${p.signature}" style="max-width:240px;border:1px solid #ccc">`:`<p style="margin-top:40px">Underskrift: ______________________________</p>`}
function reportTableHtml(reports){return `<table><tr><th>Datum</th><th>Företag</th><th>Projekt</th><th>Kund</th><th>Arbetsplats</th><th>Timmar</th><th>Km</th><th>Kostnader</th><th>Belopp</th><th>Kommentar</th><th>Bilagor</th></tr>${reports.map(r=>`<tr><td>${r.date}</td><td>${escapeHtml(entityName("companies",r.companyId))}</td><td>${escapeHtml(reportProject(r))}</td><td>${escapeHtml(entityName("customers",r.customerId))}</td><td>${escapeHtml(entityName("workplaces",r.workplaceId))}</td><td>${r.hours}</td><td>${r.km}</td><td>${reportCost(r)}</td><td>${reportPay(r)}</td><td>${escapeHtml(r.comment)}</td><td class="imgs">${(r.attachments||[]).slice(0,2).map(src=>`<img src="${src}">`).join("")}</td></tr>`).join("")}</table>`}
function exportDrivePDF(){const drives=sortedDrives();if(!drives.length)return alert("Ingen körjournal att exportera");const rows=drives.map(d=>`<tr><td>${d.date}</td><td>${escapeHtml(d.start)}</td><td>${escapeHtml(d.end)}</td><td>${escapeHtml(d.purpose)}</td><td>${d.km}</td><td>${d.rate}</td><td>${Math.round(d.km*d.rate)}</td></tr>`).join("");openPrintDoc("Körjournal",`<h1>Körjournal</h1><p>Totalt: ${total(drives,"km")} km</p><table><tr><th>Datum</th><th>Från</th><th>Till</th><th>Syfte</th><th>Km</th><th>Kr/km</th><th>Belopp</th></tr>${rows}</table>`)}
function openPrintDoc(title,body){const html=`<html><head><meta charset="UTF-8"><title>${title}</title><style>body{font-family:Arial;padding:20px}h1{color:#1565c0}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #ccc;padding:6px;text-align:left;vertical-align:top}th{background:#1565c0;color:white}.imgs img{width:80px;margin:4px;border:1px solid #ccc}@media print{button{display:none}}</style></head><body><button onclick="window.print()" style="padding:12px;margin-bottom:15px">Spara som PDF / Skriv ut</button><h1>${title}</h1>${body}<script>setTimeout(()=>window.print(),500)</script></body></html>`;const blob=new Blob([html],{type:"text/html"});location.href=URL.createObjectURL(blob)}
function exportBackup(){downloadFile("tidrapport-pro-backup.json",backupData(),"application/json;charset=utf-8")}
function downloadFile(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}