const translations={
sv:{welcome:"Välkommen",welcomeText:"Välj språk och skapa din första företagsprofil.",language:"Språk",country:"Land",currency:"Valuta",companyName:"Företagsnamn",startApp:"Starta appen",dashboard:"Start",today:"Idag",week:"Vecka",month:"Månad",costs:"Kostnader",mileage:"Körjournal",income:"Beräknad ersättning",newReport:"Ny tidrapport",newMileage:"Körjournal",calendar:"Kalender",export:"Export",recentReports:"Senaste rapporter",date:"Datum",company:"Företag",project:"Projekt",customer:"Kund",workplace:"Arbetsplats",gps:"Hämta GPS-position",startTime:"Starttid",endTime:"Sluttid",breakMinutes:"Rast minuter",calculateHours:"Beräkna timmar",hours:"Timmar",hourRate:"Timpris/timlön",km:"Kilometer",kmRate:"Ersättning per km",parking:"Parkering",toll:"Trängselskatt",material:"Material",attachments:"Bilagor/bilder",comment:"Kommentar",improveText:"Förbättra texten",save:"Spara",clear:"Rensa",mileageLog:"Körjournal",from:"Från",to:"Till",useGps:"Använd GPS",purpose:"Syfte",trips:"Resor",previous:"Föregående",next:"Nästa",selectedDay:"Vald dag",history:"Historik",clearFilters:"Rensa filter",statistics:"Statistik",totalHours:"Totalt timmar",totalKm:"Totalt km",workPay:"Arbete",kmPay:"Milersättning",byProject:"Per projekt",pdfHint:"På Android: välj Spara som PDF i utskriftsrutan.",timesheetPdf:"Tidrapport PDF",invoicePdf:"Fakturaunderlag PDF",mileagePdf:"Körjournal PDF",backup:"Säkerhetskopia JSON",importBackup:"Importera säkerhetskopia",settings:"Inställningar",profile:"Mina uppgifter",firstName:"Förnamn",lastName:"Efternamn",personalNumber:"Personnummer",phone:"Telefon",email:"E-post",address:"Adress",defaultHourRate:"Standard timpris",defaultKmRate:"Standard km-ersättning",signature:"Signatur",clearSignature:"Rensa signatur",companies:"Företag",projects:"Projekt",projectNumber:"Projektnummer",projectName:"Projektnamn",customers:"Kunder",customerName:"Kundnamn",contact:"Kontaktperson",workplaces:"Arbetsplatser",name:"Namn",add:"Lägg till",appInfo:"Appinfo",deleteReports:"Radera alla tidrapporter",home:"Start",new:"Ny",drive:"Kör",calendarShort:"Kal.",historyShort:"Hist.",statsShort:"Stat.",settingsShort:"Inst."},
en:{welcome:"Welcome",welcomeText:"Choose language and create your first company profile.",language:"Language",country:"Country",currency:"Currency",companyName:"Company name",startApp:"Start app",dashboard:"Dashboard",today:"Today",week:"Week",month:"Month",costs:"Costs",mileage:"Mileage log",income:"Estimated income",newReport:"New report",newMileage:"Mileage log",calendar:"Calendar",export:"Export",recentReports:"Recent reports",date:"Date",company:"Company",project:"Project",customer:"Customer",workplace:"Workplace",gps:"Get GPS position",startTime:"Start time",endTime:"End time",breakMinutes:"Break minutes",calculateHours:"Calculate hours",hours:"Hours",hourRate:"Hourly rate",km:"Kilometers",kmRate:"Rate per km",parking:"Parking",toll:"Toll",material:"Material",attachments:"Attachments/images",comment:"Comment",improveText:"Improve text",save:"Save",clear:"Clear",mileageLog:"Mileage log",from:"From",to:"To",useGps:"Use GPS",purpose:"Purpose",trips:"Trips",previous:"Previous",next:"Next",selectedDay:"Selected day",history:"History",clearFilters:"Clear filters",statistics:"Statistics",totalHours:"Total hours",totalKm:"Total km",workPay:"Work pay",kmPay:"Mileage pay",byProject:"By project",pdfHint:"On Android: choose Save as PDF in the print dialog.",timesheetPdf:"Timesheet PDF",invoicePdf:"Invoice basis PDF",mileagePdf:"Mileage PDF",backup:"Backup JSON",importBackup:"Import backup",settings:"Settings",profile:"My profile",firstName:"First name",lastName:"Last name",personalNumber:"Personal ID",phone:"Phone",email:"Email",address:"Address",defaultHourRate:"Default hourly rate",defaultKmRate:"Default km rate",signature:"Signature",clearSignature:"Clear signature",companies:"Companies",projects:"Projects",projectNumber:"Project number",projectName:"Project name",customers:"Customers",customerName:"Customer name",contact:"Contact person",workplaces:"Workplaces",name:"Name",add:"Add",appInfo:"App info",deleteReports:"Delete all reports",home:"Home",new:"New",drive:"Drive",calendarShort:"Cal.",historyShort:"Hist.",statsShort:"Stats",settingsShort:"Set."},
sq:{welcome:"Mirë se vini",welcomeText:"Zgjidhni gjuhën dhe krijoni profilin e parë të kompanisë.",language:"Gjuha",country:"Shteti",currency:"Valuta",companyName:"Emri i kompanisë",startApp:"Fillo aplikacionin"},
el:{welcome:"Καλώς ήρθατε",welcomeText:"Επιλέξτε γλώσσα και δημιουργήστε το πρώτο προφίλ εταιρείας.",language:"Γλώσσα",country:"Χώρα",currency:"Νόμισμα",companyName:"Όνομα εταιρείας",startApp:"Έναρξη εφαρμογής"},
de:{welcome:"Willkommen",welcomeText:"Sprache wählen und erstes Firmenprofil erstellen.",language:"Sprache",country:"Land",currency:"Währung",companyName:"Firmenname",startApp:"App starten"},
fr:{welcome:"Bienvenue",welcomeText:"Choisissez la langue et créez votre premier profil d’entreprise.",language:"Langue",country:"Pays",currency:"Devise",companyName:"Nom de l’entreprise",startApp:"Démarrer"},
es:{welcome:"Bienvenido",welcomeText:"Elija idioma y cree su primer perfil de empresa.",language:"Idioma",country:"País",currency:"Moneda",companyName:"Nombre de empresa",startApp:"Iniciar"},
it:{welcome:"Benvenuto",welcomeText:"Scegli la lingua e crea il primo profilo aziendale.",language:"Lingua",country:"Paese",currency:"Valuta",companyName:"Nome azienda",startApp:"Avvia"},
pl:{welcome:"Witamy",welcomeText:"Wybierz język i utwórz pierwszy profil firmy.",language:"Język",country:"Kraj",currency:"Waluta",companyName:"Nazwa firmy",startApp:"Uruchom"},
fi:{welcome:"Tervetuloa",welcomeText:"Valitse kieli ja luo ensimmäinen yritysprofiili.",language:"Kieli",country:"Maa",currency:"Valuutta",companyName:"Yrityksen nimi",startApp:"Aloita"}
};
function t(key){const lang=(loadDb?.().settings?.language)||localStorage.getItem("trp_lang")||"sv";return translations[lang]?.[key]||translations.en[key]||translations.sv[key]||key}
function applyLanguage(){const lang=(loadDb?.().settings?.language)||localStorage.getItem("trp_lang")||"sv";document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{el.textContent=translations[lang]?.[el.dataset.i18n]||translations.en[el.dataset.i18n]||translations.sv[el.dataset.i18n]||el.textContent})}
